development: &default
  adapter: postgresql
  database: bohokitty_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: bohokitty_test

production:
  username: deploy@104.236.87.166
  password: js281883
  host: localhost
